[workspace]
resolver = "3"
members = ["macros", "raft"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/webc-site/zenoh_raft"
homepage = "https://github.com/webc-site/zenoh_raft"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1
